#!/bin/bash
set -eu
if [ "$#" -lt 0 ]; then
	echo "missing an action"
	exit 1
fi
action="$1"
shift
base="$(dirname "$(cd "$(dirname "$0")" && pwd)")"
"$base/tools/bin/karma.sjs" "$action" tools/karma/conf.js "$@"
