#!/bin/bash
if [ -n "$NODE_PATH" ]; then
	np="$NODE_PATH:"
else
	np="";
fi

set -eu
if [ "$#" -lt 0 ]; then
	echo "missing an action"
	exit 1
fi
action="$1"
shift
base="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

export NODE_PATH="$np$base/.." # node can't find sjs from its own dir

"$base/node_modules/.bin/karma-sjs" "$action" tools/karma/conf.js "$@"
