#!/usr/bin/env node

var path = require('path');
var fs   = require('fs');
var apollo_home  = path.dirname(fs.realpathSync(__filename));

function usage() {
  process.stdout.write("Usage: apollo [options] [script.sjs [arguments]]\n\n");
  process.stdout.write("Options:\n");
  process.stdout.write("  -h, --help        display this help message\n");
  process.stdout.write("\nFor more information, please see http://bit.ly/jOy4Ms\n");
}

function execSJScript(url) {
  if (url.indexOf(":") == -1) {
    // scheme-less; we assume its a file
    url = "file:" + url;
  }
  require(apollo_home + '/oni-apollo-node').require(url, { 
    // we provide a callback to prevent nodejs from showing a useless
    // call stack when there is an error:
    callback: function(err) {
      if (err)
        console.log(err.toString());
    }
  });
}

for (var i=2; i<process.argv.length; ++i) {
  var flag = process.argv[i];
  switch (flag) {
  case "-h":
  case "--help":
    return usage();
    break;
  default:
    if (flag[0] == '-') {
      process.stdout.write("Unknown flag '"+flag+"'\n");
      return usage();
    }
    // we assume 'flag' is a script. remove everything up to now from
    // path and exec it:
    process.ARGV = process.argv = process.argv.slice(i);
    return execSJScript(flag);
  }
}

process.ARGV = process.argv = process.argv.slice(1); // remove 'node' from argv

// Drop into REPL:
require(apollo_home + '/oni-apollo-node').require('apollo:node-repl', { 
  callback: function(err, m) {if (err) throw err; m.runREPL();}
});
